### ISSUE TITLE
[BUG] Crash on macOS 10.15.7

### ISSUE THREAD

**Issue by Ectalite** [craftycodie/MineOnline#329]
**Describe the bug**
First launch I get: 
java.io.FileNotFoundException: /Users/xavierhueber/Library/Application Support/mineonline/cache/lastlogin (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at gg.codie.mineonline.utils.LastLogin.readLastLogin(LastLogin.java:67)
	at gg.codie.mineonline.gui.MenuManager.main(MenuManager.java:154)
java.io.FileNotFoundException: /Users/xavierhueber/Library/Application Support/mineonline/cache/lastlogin (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at gg.codie.mineonline.utils.LastLogin.readLastLogin(LastLogin.java:67)
	at gg.codie.mineonline.gui.screens.GuiLoginLegacy.initGui(GuiLoginLegacy.java:179)
	at gg.codie.mineonline.gui.screens.GuiLoginLegacy.<init>(GuiLoginLegacy.java:37)
	at gg.codie.mineonline.gui.MenuManager.main(MenuManager.java:240)

**To Reproduce**
Download last version (4.7.5).
Launch it from the terminal.
Wait for it to download resources.
When it wants to download the sounds it crashes (strange).
Restart it, it finishes to download the sounds.
After this it wants to open lastlogin.

**Expected behavior**
Not crash

**Screenshots**
MineOnline is stuck with a black screen after that.
<img width="858" alt="image" src="https://user-images.githubusercontent.com/31344054/170243495-dfb3693f-91f3-4558-b5bd-4075a0d2f197.png">

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: [MacOSX 10.15.7]
 - Java Version:
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
 - MineOnline Version [4.5.7]

**Comment by craftycodie** [comment]
weird, try making this folder if it doesn't exist:
`/Users/xavierhueber/Library/Application Support/mineonline/cache/`
