### ISSUE TITLE
[BUG] Game crashes on newer versions of Java.

### ISSUE THREAD

**Issue by forkiesassds** [craftycodie/MineOnline#330]
**Describe the bug**
The game crashes on newer versions of Java.

**To Reproduce**
1. Launch MineOnline using Java 17
2. Launch any version.
3. CRASH!

**Expected behavior**
The game should launch

**Screenshots**

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: Ubuntu 22.04
 - Java Version 17.0.3
 - MineOnline Version 4.7.5
 - Minecraft Version b1.1_01

**Additional context**
This may be due to the version of ASM being outdated.
```
Launching jar Beta 1.1_02 MD5 7D547E495A770C62054EF136ADD43034
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000013776, pid=60449, tid=60474
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.3+7 (17.0.3+7) (build 17.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000013776
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/user/Downloads/core.60449)
#
# An error report file with more information is saved as:
# /home/user/Downloads/hs_err_pid60449.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Preparing Patches!
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:196)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:177)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:163)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:86)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3824)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:123)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3595)
	at gg.codie.mineonline.patches.minecraft.InputPatch.init(InputPatch.java:59)
	at gg.codie.mineonline.client.LegacyGameManager.preparePatches(LegacyGameManager.java:132)
	at gg.codie.mineonline.client.LegacyGameManager.createGameManager(LegacyGameManager.java:118)
	at gg.codie.mineonline.client.LegacyMinecraftClientLauncher.startMinecraft(LegacyMinecraftClientLauncher.java:196)
	at gg.codie.mineonline.client.LegacyMinecraftClientLauncher.main(LegacyMinecraftClientLauncher.java:155)
```

**Comment by craftycodie** [comment]
Incompatible jvm

**Comment by forkiesassds** [comment]
What JVMs are compatible? I'm using the default one the OpenJDK build uses.
