### ISSUE TITLE
[BUG] b1.2_02 Non-Launcher crashes

### ISSUE THREAD

**Issue by Hedwig7s** [craftycodie/MineOnline#333]
**Describe the bug**
When trying to load the original version (not the launcher version) of b1.2_02 the game crashes

**To Reproduce**
1. Try to load b1.2_02
2. "Failed to launch Minecraft"

**Expected behavior**
The game loads

**Screenshots**
<img width="198" alt="image" src="https://user-images.githubusercontent.com/51961150/180731312-704c57aa-2860-4ec2-8042-39770b440fda.png">

**Desktop (please complete the following information):**
If you're not sure, go to the About screen in the launcher/game.
 - OS: Windows 11
 - Java Version 1.8.0_331
 - MineOnline Version 4.7.5
 - Minecraft Version b1.2_02

**Comment by craftycodie** [comment]
Works for me, perhaps your jar is corrupt.
Go to `.mineonline\versions\clients\Beta 1.2_02 08B37BCA14ACAEC18D9B9EFCFA0BAAF0` and delete the jar.

**Comment by Hedwig7s** [comment]
> Works for me, perhaps your jar is corrupt. Go to `.mineonline\versions\clients\Beta 1.2_02 08B37BCA14ACAEC18D9B9EFCFA0BAAF0` and delete the jar.

Nope it still crashes
Found this is the error log
`Launching jar Beta 1.2_02 MD5 08B37BCA14ACAEC18D9B9EFCFA0BAAF0
Preparing Patches!
java.lang.SecurityException: class "ll"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at gg.codie.mineonline.patches.minecraft.FOVViewmodelPatch.fixViewmodelFOV(FOVViewmodelPatch.java:24)
	at gg.codie.mineonline.client.LegacyGameManager.preparePatches(LegacyGameManager.java:155)
	at gg.codie.mineonline.client.LegacyGameManager.createGameManager(LegacyGameManager.java:118)
	at gg.codie.mineonline.client.LegacyMinecraftClientLauncher.startMinecraft(LegacyMinecraftClientLauncher.java:196)
	at gg.codie.mineonline.client.LegacyMinecraftClientLauncher.main(LegacyMinecraftClientLauncher.java:155)
java.io.FileNotFoundException: C:\Users\Redacted\AppData\Local\Temp\discord-rpc\discord-rpc.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at net.arikia.dev.drpc.DiscordRPC.openOutputStream(DiscordRPC.java:186)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:152)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at gg.codie.mineonline.discord.DiscordRPCHandler.lambda$initialize$1(DiscordRPCHandler.java:200)
	at java.lang.Thread.run(Unknown Source)
Could not find minecraft version b1.2_02 doublerenderdistance.jar md5: 2EDAF2E8E7B5032BA3520ED6C99FFF3C
Discord logged in Hedwig#8209!
Launching jar Beta 1.2_02 MD5 08B37BCA14ACAEC18D9B9EFCFA0BAAF0
java.io.FileNotFoundException: C:\Users\Redacted\AppData\Local\Temp\discord-rpc\discord-rpc.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at net.arikia.dev.drpc.DiscordRPC.openOutputStream(DiscordRPC.java:186)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:152)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at gg.codie.mineonline.discord.DiscordRPCHandler.lambda$initialize$1(DiscordRPCHandler.java:200)
	at java.lang.Thread.run(Unknown Source)
Preparing Patches!
java.lang.SecurityException: class "ll"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at gg.codie.mineonline.patches.minecraft.FOVViewmodelPatch.fixViewmodelFOV(FOVViewmodelPatch.java:24)
	at gg.codie.mineonline.client.LegacyGameManager.preparePatches(LegacyGameManager.java:155)
	at gg.codie.mineonline.client.LegacyGameManager.createGameManager(LegacyGameManager.java:118)
	at gg.codie.mineonline.client.LegacyMinecraftClientLauncher.startMinecraft(LegacyMinecraftClientLauncher.java:196)
	at gg.codie.mineonline.client.LegacyMinecraftClientLauncher.main(LegacyMinecraftClientLauncher.java:155)`
